### PR TITLE
Docker build

### PR DESCRIPTION
**Pull request by james-bird**
Hi, 

I was using DICe on linux and it can be a bit tricky to build with all the dependancies. 

I packaged it up (version 2.0) into a docker container and thought I would share as I found it useful.

It's quite a long way behind master because its based off v2.0, so a new branch might be necessary. 

If you have any thoughts (or even if it's not really useful to the official project) let me know. 

Best wishes, 

James

### CODE REVIEW

**Comment by dicengine** [comment]
Thanks for the work on the docker build for DICe. This is really helpful. There are a couple issues with the pull request that we need to figure out how to deal with:

1. We don't have much flexibility for using the https protocol for the hypercine repo in CMakeLists.txt. Is there something about docker that requires this change?
2. The whiltespace change to README.md should be removed.

The rest of the changes seem appropriate for merging.

How hard would it be to update the docker instance for the most current version of DICe?

**Comment by james-bird** [comment]
I was having a bit of trouble with the ssh authentication using docker. I am sure its solvable, but it was easier to just change to https. I'll have a look at the underlying issue and revert it back to ssh.

I'll also sort out the whitespace. I'm not sure what happened there!

**Comment by james-bird** [comment]
I have changed `CMakeLists` back to ssh. The SSH private key is passed as a secret in the repo so the GitHub action can build the image. 

Also fixed the white space in the ReadMe

**Comment by dicengine** [comment]
Thanks for making the updates! Looks good. I've merged the pull request.

**Comment by james-bird** [comment]
No problem. The GitHub action should build and publish the docker image. You might have to add a key for the SSH_KEY secret to the repo for it to build and publish for you. Let me know if there are any issues.
James

**Pull request merged**
