### PR TITLE
Docker v2p0

### PR DESCRIPTION
**Pull request by james-bird**

### CODE REVIEW

**Comment by dicengine** [comment]
I created the SSH_KEY secret with the private key corresponding to a public deployment ssh key, but the docker build check is failing for some reason. I think you can follow the links above to see the error message, but it has to do with the ssh-private-key argument being empty. I don't know how to fix this.

**Comment by dicengine** [comment]
Where did you store the SSH_KEY secret in your example that worked? I have it stored in both the dicengine/dice.git repo and the dicengine/hypercine.git repos, but for some reason the ssh-private-key variable in the workflow still comes up empty generating the same error.

**Comment by james-bird** [comment]
I stored the public key in the Deploy keys section of the hypercine repo, and then stored the private key as a repository secret (Settings->Secrets->Actions) in the dice repo with the title SSH_KEY.

**Comment by dicengine** [comment]
I'm doing exactly the same, but for some reason the workflow run for the pull request test doesn't see the SSH_KEY secret in the dice repo. I wonder if it has something to do with the branch the pull request is on.

**Comment by james-bird** [comment]
That is really weird. Maybe it can't see it until it has been merged?

**Comment by james-bird** [comment]
It seems like for security reasons secrets are not passed to workflows when the pull request is from a forked repo. Apart from GITHUB_TOKEN.
https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by dicengine** [comment]
See if it works now that it's merged. At least we learned a lot about secrets and workflows...

**Comment by J-C-Haley** [comment]
Did this work after merge? I'm trying to use the docker branch as an example for building out my own container with DICe using Ubuntu 20.04, the hypercine clone is failing due to a 'Permission denied (publickey)'

**Pull request merged**
